name: VoidSpawnPlus
version: '${project.version}'
main: com.voidspawn.VoidSpawn
api-version: '1.20'
folia-supported: true
description: Optimized void spawn teleport plugin
author: amhunter1 (melüt) Lora Technologies

commands:
  vs:
    description: VoidSpawn main command
    usage: /<command> [setspawn|reload]
    permission: voidspawn.admin
    aliases: [voidspawn]

permissions:
  voidspawn.admin:
    description: Allows access to admin commands
    default: op
  voidspawn.bypass:
    description: Bypass void teleportation
    default: false
